//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrySecondInter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public long Id { get; set; }
        public long SenderId { get; set; }
        public long RecieverId { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
